name: Benchmark
on:
  pull_request_target:
    types: [labeled]

jobs:
  pr-benchmark:
    if: ${{ github.event.label.name == 'benchmark' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Benchmark
        id: benchmark-pr
        run: |
          README_TEXT=$(cat ./README.md)
          echo "::set-output name=README::$README_TEXT"

      # main benchmark
      - uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Benchmark
        id: benchmark-main
        run: |
          README_TEXT=$(cat ./README.md)
          echo "::set-output name=README::$README_TEXT"
          
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "PR: ${{ steps.benchmark-pr.outputs.README }}\nMAIN: ${{ steps.benchmark-main.outputs.README }}"

      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            benchmark
          github_token: ${{ secrets.GITHUB_TOKEN }}
